### ISSUE TITLE
@AutoValue.Builder isn't coming through in 1.2

### ISSUE THREAD

**Issue by ZacSweers** [JakeWharton/AutoValueAnnotations#1]
![screenshot 2016-06-18 13 22 06](https://cloud.githubusercontent.com/assets/1361086/16173493/9d0dc4d0-3557-11e6-8de4-dac96f9a2a18.png)

When it should be pulling in the [internal Builder](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/AutoValue.java#L46-L73) annotation as well.

**Comment by JakeWharton** [comment]
Use 1.2-update1

**Comment by ZacSweers** [comment]
Oh god I'm stupid. For some reason I thought -update1 was older. 😳

**Comment by JakeWharton** [comment]
Once 1.3 is released I'll release a new version here so it matches.
