### ISSUE TITLE
Package AutoFactory and AutoService annotations

### ISSUE THREAD

**Issue by lukaciko** [JakeWharton/AutoValueAnnotations#2]
The [google/auto](https://github.com/google/auto) project has two other subprojects that also don't package annotations independently, [AutoFactory](https://github.com/google/auto/tree/master/factory) and [AutoService](https://github.com/google/auto/tree/master/service). It'd be great if those annotations could be as easily included as `@AutoValue` is now with this project. They should probably live in different artifacts with artifact IDs `auto-factory-annotations` and `auto-service-annotations`. 

The annotations in these subprojects are:
* `com.google.auto.factory.AutoFactory`
* `com.google.auto.factory.Provided`
* `com.google.auto.service.AutoService`

It'd be a nicer fit if this project was called `AutoAnnotations` but perhaps it's a good enough until Google breaks up the dependencies.

**Comment by JakeWharton** [comment]
Yeah I think I can accommodate.

Although AutoAnnotations is a bad name because AutoValue itself has a
sibling called AutoAnnotation which will lead to confusion. We can come up
with something, though.

**Comment by JakeWharton** [comment]
See https://github.com/JakeWharton/AutoValueAnnotations/pull/8#issuecomment-376316429
