### ISSUE TITLE
Proguard Config

### ISSUE THREAD

**Issue by naturalwarren** [JakeWharton/AutoValueAnnotations#7]
Does this project need a proguard config to suppress this warning? After bumping to 1.5 I'm seeing these warnings all over the place:

```
WARNING: can't find referenced class com.google.auto.value.AutoValue
```

**Comment by JakeWharton** [comment]
That class is inside this artifact so I'm not sure why we would want to suppress a warning about it.

**Comment by naturalwarren** [comment]
I would have thought other folks would be seeing this too. I'm not sure why it has arisen after bumping to 1.5; perhaps because 1.5 requires the compiler to be Java 8 or later? After suppressing the warning everything works fine.

**Comment by JakeWharton** [comment]
Do you have a project that reproduces the problem?

**Comment by naturalwarren** [comment]
I'll setup a sample project and link it here. If it doesn't reproduce I'll close this out.

Thanks Jake.

**Comment by simon04** [comment]
This is due to [AutoValue 1.5](https://github.com/google/auto/releases/tag/auto-value-1.5) have changed the retention of the `@AutoValue` annotation from `SOURCE` to `CLASS`.

**Comment by naturalwarren** [comment]
Closing this out since I haven't take any additional action against it and others haven't reported it as an issue.

**Comment by Kisty** [comment]
Having same problem. Using `compileOnly` on the artefact fails when using proguard:
`Warning: uk.co.imagitech.mediaserver.AuthCredentials: can't find referenced class com.google.auto.value.AutoValue`
and thus fails the build.

However, changing to `implementation` on it does work. Is that expected?

Am using it in a library module in my project.

**Comment by JakeWharton** [comment]
Yes. The annotation retention is now CLASS instead of SOURCE. You can also
suppress the warning to avoid having to package the annotations.
